# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.19 is version 41
loaderVersion="[41,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"

[[mods]]
  modId="tutorialmod"
  version="1.0.0.0"
  displayName="Tutorial Mod :v"
  #updateJSONURL=""
  #displayURL=""
  logoFile=""
  credits="Like y suscribe!!"
  authors="Codigo Morsa"
  description='''
  Raza estamos de vuelta con los mods de Minecraft
  '''